### ISSUE TITLE
Follow View setting wrong

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/fa5indy#2]
One of the Follow View camera settings for Tri-motor in AFFS4 results in the aircraft be suspended above the hot start taxi location at IYK as shown.
![20221202183448_1](https://user-images.githubusercontent.com/69315126/205418514-8f3cbd9e-63b9-4c57-abd7-df9a8c1692cc.jpg)

**Comment by krzysk1** [comment]
follow camera fixed. Thank you for report
